"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$package$nodejs$ruby$aws
$character"""

[aws]
format = "on [$symbol$profile]($style) "
style = "bold #fab387"
symbol = "îŒ½ "
force_display = true

[git_branch]
symbol = "ï˜ "

[nodejs]
symbol = "ó°™ "

[package]
symbol = "ó°– "
format = "is [$symbol$version]($style) "
display_private = true
style = "#fab387"

[ruby]
symbol = "î‘ "

[directory]
style = "bold #fab387"

[character]
success_symbol = "[ğ³](bold fg:#89b4fa)"
error_symbol = "[ğ³](bold fg:#f38ba8)"
